author:
  name: Jess Dolan
  role: PhD in Philosophy
  bio:  Known for contributions to phenomenology, hermeneutics, and existentialism.
  location: Munich, Germany

social:
  - id: "instagram"
    label: "Instagram"
    href: "#_"
  - id: "linkedin"
    label: "Linkedin"
    href: "#_"
  - id: "email"
    label: "Email"
    href: "mailto:"